version: '3'

services:
  node:
    image: witnet/witnet-rust
    restart: unless-stopped
    ports:
      - "21337:21337"
    volumes:
      - "$HOME/.witnet:/.witnet:rw"
  node2:
    image: witnet/witnet-rust
    restart: unless-stopped
    ports:
      - "22337:21337"
    volumes:
      - "$HOME/.witnet2:/.witnet:rw"
  node3:
    image: witnet/witnet-rust
    restart: unless-stopped
    ports:
      - "23337:21337"
    volumes:
      - "$HOME/.witnet3:/.witnet:rw"
  node4:
    image: witnet/witnet-rust
    restart: unless-stopped
    ports:
      - "24337:21337"
    volumes:
      - "$HOME/.witnet4:/.witnet:rw"
  node5:
    image: witnet/witnet-rust
    restart: unless-stopped
    ports:
      - "25337:21337"
    volumes:
      - "$HOME/.witnet5:/.witnet:rw"
  node6:
    image: witnet/witnet-rust
    restart: unless-stopped
    ports:
      - "26337:21337"
    volumes:
      - "$HOME/.witnet6:/.witnet:rw"
  node7:
    image: witnet/witnet-rust
    restart: unless-stopped
    ports:
      - "27337:21337"
    volumes:
      - "$HOME/.witnet7:/.witnet:rw"
  node8:
    image: witnet/witnet-rust
    restart: unless-stopped
    ports:
      - "28337:21337"
    volumes:
      - "$HOME/.witnet8:/.witnet:rw"
